org: johnholden
app: tree-epidemic-sim
service: tree-epidemic-sim

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  region: eu-west-2
  runtime: python3.8

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
