org: johnholden
app: tree-epidemic-sim
service: tree-epidemic-sim

frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-2
  runtime: python3.8
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: { "Fn::Join": [ "", [ "arn:aws:s3:::tree-epi-site-bucket", "/*" ] ] }

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 300  #  default is 6(s)
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    package:
      patterns:
        - tree_epi_back/**
        - app.py

custom:
  wsgi:
    app: app.app

package:
  individually: true
  patterns:
    - '!./**'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
