org: johnholden
app: tree-epidemic-sim
service: tree-epidemic-sim

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  region: eu-west-2
  runtime: python3.8
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: { "Fn::Join": [ "", [ "arn:aws:s3:::tree-epi-site-bucket", "/*" ] ] }

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    package:
      include:
        - app.py

package:
  individually: true
  exclude:
    - ./**

plugins:
  - serverless-wsgi
  - serverless-python-requirements